// src/routes/player/+page.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { page } from '$app/stores';
	import { getTablaPlayer, unlockAudio } from '$lib/audio';
	import { playback } from '$lib/stores/playback';
	import { parseComposition, rowsToText } from '$lib/utils/bolParser';
	import { getCompositions, getComposition, createComposition } from '$lib/firebase/db';
	import BolGrid from '$lib/components/BolGrid.svelte';
	import PlaybackControls from '$lib/components/PlaybackControls.svelte';
	import TaalSelector from '$lib/components/TaalSelector.svelte';
	import type { Row, Composition } from '$lib/types';
	import * as Tone from 'tone';

	// State
	let bolInput = $state('Dha Dhin Dhin Dha | Dha Dhin Dhin Dha\nDha Tin Tin Ta | Ta Dhin Dhin Dha');
	let rows = $state<Row[]>([]);
	let audioReady = $state(false);
	let compositions = $state<Composition[]>([]);
	let saveTitle = $state('');
	let saveTaal = $state('Teentaal');
	let isSaving = $state(false);
	let saveMessage = $state('');
	let loadedCompositionId = $state<string | null>(null);

	// Derived from store
	let isPlaying = $state(false);
	let currentBeat = $state(0);
	let currentRow = $state(0);
	let tempo = $state(60);

	// Subscribe to playback store
	const unsubscribe = playback.subscribe((state) => {
		isPlaying = state.isPlaying;
		currentBeat = state.currentBeat;
		currentRow = state.currentRow;
		tempo = state.tempo;
	});

	// Scheduler variables
	let schedulerInterval: ReturnType<typeof setInterval> | null = null;
	let nextNoteTime = 0;
	const scheduleAheadTime = 0.1; // Schedule 100ms ahead
	const lookahead = 25; // Check every 25ms

	// Parse bols when input changes
	$effect(() => {
		rows = parseComposition(bolInput);
	});

	// Handle playback scheduling
	function scheduler() {
		const tabla = getTablaPlayer();
		if (!tabla.ready || rows.length === 0) return;

		while (nextNoteTime < Tone.now() + scheduleAheadTime) {
			// Get current bol
			const row = rows[currentRow];
			if (row && row.beats[currentBeat]) {
				const beat = row.beats[currentBeat];
				beat.bols.forEach((bol) => {
					if (bol !== '-') {
						tabla.playBol(bol, nextNoteTime);
					}
				});
			}

			// Advance position
			const totalBeats = rows[currentRow]?.beats.length || 1;
			playback.advance(totalBeats, rows.length);

			// Calculate next note time
			nextNoteTime += 60 / tempo;
		}
	}

	async function handlePlay() {
		if (!audioReady) {
			await initAudio();
		}

		if (rows.length === 0) return;

		nextNoteTime = Tone.now() + 0.05;
		playback.play();
		schedulerInterval = setInterval(scheduler, lookahead);
	}

	function handlePause() {
		playback.pause();
		if (schedulerInterval) {
			clearInterval(schedulerInterval);
			schedulerInterval = null;
		}
	}

	function handleStop() {
		handlePause();
		playback.stop();
	}

	function handleTempoChange(newTempo: number) {
		playback.setTempo(newTempo);
	}

	async function initAudio() {
		await unlockAudio();
		const tabla = getTablaPlayer();
		await tabla.init();
		audioReady = true;
	}

	async function loadCompositions() {
		try {
			compositions = await getCompositions();
		} catch (e) {
			console.error('Failed to load compositions:', e);
		}
	}

	function loadComposition(comp: Composition) {
		bolInput = rowsToText(comp.rows);
		playback.setTempo(comp.meta.tempo);
		handleStop();
	}

	async function saveComposition() {
		if (!saveTitle.trim()) {
			saveMessage = 'Please enter a title';
			return;
		}

		isSaving = true;
		saveMessage = '';

		try {
			await createComposition({
				meta: {
					title: saveTitle,
					taal: saveTaal,
					tempo: tempo
				},
				rows: rows
			});
			saveMessage = 'Saved!';
			saveTitle = '';
			await loadCompositions();
		} catch (e) {
			console.error('Failed to save:', e);
			saveMessage = 'Failed to save. Check Firebase config.';
		} finally {
			isSaving = false;
		}
	}

	onMount(async () => {
		loadCompositions();

		// Check for composition ID in URL
		const loadId = $page.url.searchParams.get('load');
		if (loadId) {
			try {
				const comp = await getComposition(loadId);
				if (comp) {
					loadComposition(comp);
					loadedCompositionId = comp.id;
				}
			} catch (e) {
				console.error('Failed to load composition:', e);
			}
		}
	});

	onDestroy(() => {
		unsubscribe();
		handleStop();
	});
</script>

<svelte:head>
	<title>Tabla Player - Play Compositions</title>
</svelte:head>

<main class="min-h-screen bg-gradient-to-b from-amber-50 to-orange-100 font-sans">
	<div class="container mx-auto px-4 py-8 max-w-4xl">
		<nav class="mb-8">
			<a href="/" class="text-amber-600 hover:text-amber-800">&larr; Back to Home</a>
		</nav>

		<h1 class="text-4xl font-bold text-amber-900 mb-8">Tabla Player</h1>

		<!-- Audio unlock prompt -->
		{#if !audioReady}
			<button
				onclick={initAudio}
				class="w-full mb-6 p-4 bg-amber-100 border-2 border-amber-300 rounded-xl text-amber-800 hover:bg-amber-200 transition-colors"
			>
				Tap to Enable Audio
			</button>
		{/if}

		<!-- Playback Controls -->
		<div class="mb-6">
			<PlaybackControls
				{isPlaying}
				{tempo}
				onPlay={handlePlay}
				onPause={handlePause}
				onStop={handleStop}
				onTempoChange={handleTempoChange}
				disabled={rows.length === 0}
			/>
		</div>

		<!-- Bol Grid Display -->
		<div class="mb-6 p-4 bg-white rounded-2xl shadow-lg border-2 border-amber-200">
			<h2 class="text-xl font-semibold text-amber-900 mb-4">Composition</h2>
			<BolGrid {rows} {currentRow} {currentBeat} beatsPerRow={4} />
		</div>

		<!-- Bol Input -->
		<div class="mb-6 p-4 bg-white rounded-2xl shadow-lg border-2 border-amber-200">
			<h2 class="text-xl font-semibold text-amber-900 mb-4">Enter Bols</h2>
			<textarea
				bind:value={bolInput}
				rows="4"
				placeholder="Enter bols separated by spaces. Use | for visual grouping. New line for new row.&#10;Example: Dha Dhin Dhin Dha | Dha Dhin Dhin Dha"
				class="w-full p-3 border-2 border-amber-200 rounded-lg font-mono text-amber-900 focus:border-amber-400 focus:outline-none resize-none"
			></textarea>
			<p class="mt-2 text-sm text-amber-600">
				Supported bols: Dha, Dhin, Ta, Tin, Na, Tun, Ge, Ke, Ti, Te, Ra, Ka, Tete, Gadi, Trkt, - (rest)
			</p>
		</div>

		<!-- Save Section -->
		<div class="mb-6 p-4 bg-white rounded-2xl shadow-lg border-2 border-amber-200">
			<h2 class="text-xl font-semibold text-amber-900 mb-4">Save Composition</h2>
			<div class="flex flex-col sm:flex-row gap-3">
				<input
					type="text"
					bind:value={saveTitle}
					placeholder="Composition title"
					class="flex-1 p-2 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none"
				/>
				<TaalSelector bind:value={saveTaal} />
				<button
					onclick={saveComposition}
					disabled={isSaving || rows.length === 0}
					class="px-6 py-2 bg-amber-500 hover:bg-amber-600 disabled:bg-gray-300 text-white rounded-lg font-semibold transition-colors"
				>
					{isSaving ? 'Saving...' : 'Save'}
				</button>
			</div>
			{#if saveMessage}
				<p class="mt-2 text-sm" class:text-green-600={saveMessage === 'Saved!'} class:text-red-600={saveMessage !== 'Saved!'}>
					{saveMessage}
				</p>
			{/if}
		</div>

		<!-- Saved Compositions -->
		{#if compositions.length > 0}
			<div class="p-4 bg-white rounded-2xl shadow-lg border-2 border-amber-200">
				<h2 class="text-xl font-semibold text-amber-900 mb-4">Saved Compositions</h2>
				<div class="space-y-2">
					{#each compositions as comp}
						<button
							onclick={() => loadComposition(comp)}
							class="w-full p-3 text-left bg-amber-50 hover:bg-amber-100 rounded-lg transition-colors"
						>
							<span class="font-semibold text-amber-900">{comp.meta.title || 'Untitled'}</span>
							<span class="text-amber-600 ml-2">{comp.meta.taal} - {comp.meta.tempo} BPM</span>
						</button>
					{/each}
				</div>
			</div>
		{/if}
	</div>
</main>

// src/app/player/page.tsx
'use client';

import { useState, useEffect, useRef, useCallback, Suspense } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import * as Tone from 'tone';
import AudioUnlockButton from '@/components/AudioUnlockButton';
import BolGrid from '@/components/BolGrid';
import PlaybackControls from '@/components/PlaybackControls';
import TempoInput from '@/components/TempoInput';
import { getTablaPlayer } from '@/lib/audio/tabla';
import { getCompositions, getComposition } from '@/lib/firebase/db';
import { parseComposition, getAllBols } from '@/lib/parser';
import type { Row, Composition } from '@/lib/types';

function PlayerContent() {
  const searchParams = useSearchParams();
  const loadId = searchParams.get('load');

  const [audioUnlocked, setAudioUnlocked] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [tempo, setTempo] = useState(60);
  const [currentRow, setCurrentRow] = useState(-1);
  const [currentBeat, setCurrentBeat] = useState(-1);
  const [rows, setRows] = useState<Row[]>([]);
  const [bolInput, setBolInput] = useState('');
  const [title, setTitle] = useState('');
  const [loading, setLoading] = useState(false);

  // Composition selector
  const [compositions, setCompositions] = useState<Composition[]>([]);
  const [selectedId, setSelectedId] = useState<string>('');
  const [showSelector, setShowSelector] = useState(false);

  const schedulerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const nextNoteTimeRef = useRef(0);
  const currentBolIndexRef = useRef(0);

  // Load all compositions for selector
  useEffect(() => {
    getCompositions().then(setCompositions);
  }, []);

  // Load composition if ID provided via URL or selector
  useEffect(() => {
    const idToLoad = loadId || selectedId;
    if (idToLoad) {
      setLoading(true);
      getComposition(idToLoad)
        .then((comp) => {
          if (comp) {
            setRows(comp.rows);
            setTitle(comp.meta.title || '');
            setTempo(comp.meta.tempo || 60);
            setBolInput('');
            setShowSelector(false);
          }
        })
        .finally(() => setLoading(false));
    }
  }, [loadId, selectedId]);

  // Parse bol input
  useEffect(() => {
    if (bolInput.trim()) {
      const parsed = parseComposition(bolInput);
      setRows(parsed);
      setTitle('');
    }
  }, [bolInput]);

  const stopPlayback = useCallback(() => {
    if (schedulerRef.current) {
      clearInterval(schedulerRef.current);
      schedulerRef.current = null;
    }
    setIsPlaying(false);
    setCurrentRow(-1);
    setCurrentBeat(-1);
    currentBolIndexRef.current = 0;
  }, []);

  const startPlayback = useCallback(async () => {
    if (rows.length === 0) return;

    const player = getTablaPlayer();
    if (!player.ready) {
      await player.init();
    }

    const allBols = getAllBols(rows);
    if (allBols.length === 0) return;

    const beatDuration = 60 / tempo;
    const scheduleAheadTime = 0.1;
    const lookahead = 25;

    currentBolIndexRef.current = 0;
    nextNoteTimeRef.current = Tone.now() + 0.1;

    const scheduler = () => {
      while (nextNoteTimeRef.current < Tone.now() + scheduleAheadTime) {
        const bolIndex = currentBolIndexRef.current;
        const bol = allBols[bolIndex];

        // Calculate row and beat position
        let remaining = bolIndex;
        let rowIdx = 0;
        let beatIdx = 0;
        for (let r = 0; r < rows.length; r++) {
          if (remaining < rows[r].beats.length) {
            rowIdx = r;
            beatIdx = remaining;
            break;
          }
          remaining -= rows[r].beats.length;
        }

        // Schedule the sound
        player.playBol(bol, nextNoteTimeRef.current);

        // Update UI
        setCurrentRow(rowIdx);
        setCurrentBeat(beatIdx);

        // Advance
        nextNoteTimeRef.current += beatDuration;
        currentBolIndexRef.current = (bolIndex + 1) % allBols.length;
      }
    };

    schedulerRef.current = setInterval(scheduler, lookahead);
    setIsPlaying(true);
  }, [rows, tempo]);

  const handlePlay = () => {
    if (!isPlaying) startPlayback();
  };

  const handlePause = () => {
    if (schedulerRef.current) {
      clearInterval(schedulerRef.current);
      schedulerRef.current = null;
    }
    setIsPlaying(false);
  };

  const clearComposition = () => {
    setRows([]);
    setTitle('');
    setBolInput('');
    setSelectedId('');
    stopPlayback();
  };

  return (
    <main className="min-h-screen p-4 sm:p-8">
      {!audioUnlocked && <AudioUnlockButton onUnlock={() => setAudioUnlocked(true)} />}

      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <header className="flex items-center justify-between mb-6">
          <Link
            href="/"
            className="text-amber-600 hover:text-amber-800 font-medium"
          >
            ← Home
          </Link>
          <h1 className="text-2xl font-bold text-amber-900">
            {title || 'Player'}
          </h1>
          <div className="w-16" />
        </header>

        {loading ? (
          <div className="text-center text-amber-600 py-12">Loading...</div>
        ) : (
          <>
            {/* Composition Selector */}
            <div className="bg-white rounded-2xl shadow-lg border-2 border-amber-200 p-4 mb-6">
              <div className="flex flex-wrap items-center gap-3">
                <button
                  onClick={() => setShowSelector(!showSelector)}
                  className="px-4 py-2 bg-amber-100 text-amber-700 rounded-xl font-medium hover:bg-amber-200 active:scale-95 transition-all"
                >
                  {showSelector ? 'Hide List' : 'Load Composition'}
                </button>
                {title && (
                  <>
                    <span className="text-amber-600">Playing: <strong className="text-amber-900">{title}</strong></span>
                    <button
                      onClick={clearComposition}
                      className="text-amber-500 hover:text-amber-700 text-sm"
                    >
                      Clear
                    </button>
                  </>
                )}
              </div>

              {showSelector && (
                <div className="mt-4 max-h-60 overflow-y-auto border-t border-amber-100 pt-4">
                  {compositions.length === 0 ? (
                    <p className="text-amber-500 text-sm">No compositions found</p>
                  ) : (
                    <div className="space-y-2">
                      {compositions.map((comp) => (
                        <button
                          key={comp.id}
                          onClick={() => setSelectedId(comp.id)}
                          className={`w-full text-left p-3 rounded-xl transition-all ${
                            selectedId === comp.id
                              ? 'bg-amber-500 text-white'
                              : 'bg-amber-50 hover:bg-amber-100 text-amber-900'
                          }`}
                        >
                          <div className="font-medium">{comp.meta.title || 'Untitled'}</div>
                          <div className={`text-sm ${selectedId === comp.id ? 'text-amber-100' : 'text-amber-500'}`}>
                            {comp.meta.taal} · {comp.meta.tempo} BPM
                          </div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Bol Input (manual entry) */}
            {!title && (
              <div className="mb-6">
                <label className="block text-amber-700 font-medium mb-2">
                  Or enter bols manually
                </label>
                <textarea
                  value={bolInput}
                  onChange={(e) => setBolInput(e.target.value)}
                  placeholder="Dha Dhin Dhin Dha | Dha Dhin Dhin Dha&#10;Dha Tin Tin Ta | Ta Dhin Dhin Dha"
                  className="w-full p-3 bg-white border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none min-h-[100px] font-mono"
                />
              </div>
            )}

            {/* Bol Grid */}
            <div className="bg-white rounded-2xl shadow-lg border-2 border-amber-200 p-4 sm:p-6 mb-6">
              {rows.length > 0 ? (
                <BolGrid
                  rows={rows}
                  currentRow={currentRow}
                  currentBeat={currentBeat}
                />
              ) : (
                <p className="text-center text-amber-500 py-8">
                  Select a composition or enter bols above
                </p>
              )}
            </div>

            {/* Tempo Input */}
            <div className="flex justify-center mb-8">
              <TempoInput tempo={tempo} onChange={setTempo} />
            </div>

            {/* Playback Controls */}
            <PlaybackControls
              isPlaying={isPlaying}
              onPlay={handlePlay}
              onPause={handlePause}
              onStop={stopPlayback}
              disabled={rows.length === 0}
            />
          </>
        )}
      </div>
    </main>
  );
}

export default function PlayerPage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center text-amber-600">Loading...</div>}>
      <PlayerContent />
    </Suspense>
  );
}
