// src/app/upload/page.tsx
'use client';

import { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import BolGrid from '@/components/BolGrid';
import TaalSelector from '@/components/TaalSelector';
import TempoSlider from '@/components/TempoSlider';
import { parseComposition } from '@/lib/parser';
import {
  createComposition,
  getComposition,
  updateComposition,
} from '@/lib/firebase/db';
import type { Row } from '@/lib/types';

function UploadContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const editId = searchParams.get('edit');

  const [title, setTitle] = useState('');
  const [taal, setTaal] = useState('Teentaal');
  const [tempo, setTempo] = useState(60);
  const [bolInput, setBolInput] = useState('');
  const [author, setAuthor] = useState('');
  const [description, setDescription] = useState('');
  const [tagsInput, setTagsInput] = useState('');
  const [rows, setRows] = useState<Row[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  // Load composition for editing
  useEffect(() => {
    if (editId) {
      setLoading(true);
      getComposition(editId)
        .then((comp) => {
          if (comp) {
            setTitle(comp.meta.title || '');
            setTaal(comp.meta.taal || 'Teentaal');
            setTempo(comp.meta.tempo || 60);
            setAuthor(comp.meta.author || '');
            setDescription(comp.meta.description || '');
            setTagsInput(comp.meta.tags?.join(', ') || '');
            // Convert rows back to text
            const text = comp.rows
              .map((row) =>
                row.beats.map((beat) => beat.bols.join('')).join(' ')
              )
              .join('\n');
            setBolInput(text);
            setRows(comp.rows);
          }
        })
        .finally(() => setLoading(false));
    }
  }, [editId]);

  // Parse bol input
  useEffect(() => {
    if (bolInput.trim()) {
      const parsed = parseComposition(bolInput);
      setRows(parsed);
    } else {
      setRows([]);
    }
  }, [bolInput]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!title.trim()) {
      setError('Title is required');
      return;
    }

    if (rows.length === 0) {
      setError('Please enter some bols');
      return;
    }

    if (tempo < 20 || tempo > 300) {
      setError('Tempo must be between 20 and 300 BPM');
      return;
    }

    setSaving(true);

    try {
      const tags = tagsInput
        .split(',')
        .map((t) => t.trim().toLowerCase())
        .filter(Boolean);

      const data = {
        meta: {
          title: title.trim(),
          taal,
          tempo,
          author: author.trim() || undefined,
          description: description.trim() || undefined,
          tags: tags.length > 0 ? tags : undefined,
        },
        rows,
      };

      if (editId) {
        await updateComposition(editId, data);
      } else {
        await createComposition(data);
      }

      router.push('/browse');
    } catch (err) {
      setError('Failed to save composition');
      console.error(err);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <main className="min-h-screen p-4 sm:p-8">
        <div className="max-w-4xl mx-auto text-center text-amber-600 py-12">
          Loading...
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen p-4 sm:p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <header className="flex items-center justify-between mb-6">
          <Link
            href="/browse"
            className="text-amber-600 hover:text-amber-800 font-medium"
          >
            ← Browse
          </Link>
          <h1 className="text-2xl font-bold text-amber-900">
            {editId ? 'Edit Composition' : 'New Composition'}
          </h1>
          <div className="w-16" />
        </header>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Title */}
          <div>
            <label className="block text-amber-700 font-medium mb-2">
              Title *
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., Teentaal Theka"
              className="w-full p-3 bg-white border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none"
            />
          </div>

          {/* Taal & Tempo */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <TaalSelector value={taal} onChange={setTaal} />
            <div>
              <TempoSlider tempo={tempo} onChange={setTempo} />
            </div>
          </div>

          {/* Bols Input */}
          <div>
            <label className="block text-amber-700 font-medium mb-2">
              Bols *
            </label>
            <textarea
              value={bolInput}
              onChange={(e) => setBolInput(e.target.value)}
              placeholder="Dha Dhin Dhin Dha | Dha Dhin Dhin Dha&#10;Dha Tin Tin Ta | Ta Dhin Dhin Dha"
              className="w-full p-3 bg-white border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none min-h-[120px] font-mono"
            />
            <p className="text-amber-500 text-sm mt-1">
              Separate bols with spaces. Use | for visual grouping. New line for
              new row.
            </p>
          </div>

          {/* Preview */}
          {rows.length > 0 && (
            <div className="bg-white rounded-2xl shadow-lg border-2 border-amber-200 p-4">
              <h3 className="text-amber-700 font-medium mb-3">Preview</h3>
              <BolGrid rows={rows} />
            </div>
          )}

          {/* Author */}
          <div>
            <label className="block text-amber-700 font-medium mb-2">
              Author
            </label>
            <input
              type="text"
              value={author}
              onChange={(e) => setAuthor(e.target.value)}
              placeholder="Your name (optional)"
              className="w-full p-3 bg-white border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none"
            />
          </div>

          {/* Description */}
          <div>
            <label className="block text-amber-700 font-medium mb-2">
              Description
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Brief description (optional)"
              className="w-full p-3 bg-white border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none min-h-[80px]"
            />
          </div>

          {/* Tags */}
          <div>
            <label className="block text-amber-700 font-medium mb-2">
              Tags
            </label>
            <input
              type="text"
              value={tagsInput}
              onChange={(e) => setTagsInput(e.target.value)}
              placeholder="theka, beginner, teentaal (comma separated)"
              className="w-full p-3 bg-white border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none"
            />
          </div>

          {/* Error */}
          {error && (
            <div className="bg-red-50 border-2 border-red-200 text-red-700 p-4 rounded-xl">
              {error}
            </div>
          )}

          {/* Submit */}
          <button
            type="submit"
            disabled={saving}
            className="w-full p-4 bg-amber-500 text-white rounded-xl font-semibold hover:bg-amber-600 active:scale-[0.98] transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {saving ? 'Saving...' : editId ? 'Update Composition' : 'Save Composition'}
          </button>
        </form>
      </div>
    </main>
  );
}

export default function UploadPage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center text-amber-600">Loading...</div>}>
      <UploadContent />
    </Suspense>
  );
}

// src/routes/upload/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { createComposition, getComposition, updateComposition } from '$lib/firebase/db';
	import { parseComposition, rowsToText } from '$lib/utils/bolParser';
	import TaalSelector from '$lib/components/TaalSelector.svelte';
	import BolGrid from '$lib/components/BolGrid.svelte';
	import type { Row } from '$lib/types';

	// Edit mode
	let editId = $state<string | null>(null);
	let isEditMode = $derived(!!editId);
	let isLoading = $state(false);

	// Form state
	let title = $state('');
	let taal = $state('Teentaal');
	let tempo = $state(60);
	let description = $state('');
	let author = $state('');
	let tagsInput = $state('');
	let bolInput = $state('');

	// UI state
	let isSubmitting = $state(false);
	let errorMessage = $state('');
	let successMessage = $state('');

	// Parsed preview
	let rows = $state<Row[]>([]);
	let parseError = $state('');

	// Parse bols when input changes
	$effect(() => {
		if (bolInput.trim()) {
			try {
				rows = parseComposition(bolInput);
				parseError = rows.length === 0 ? 'No valid bols found' : '';
			} catch (e) {
				parseError = 'Failed to parse composition';
				rows = [];
			}
		} else {
			rows = [];
			parseError = '';
		}
	});

	// Load composition for editing
	async function loadComposition(id: string) {
		isLoading = true;
		errorMessage = '';

		try {
			const comp = await getComposition(id);
			if (comp) {
				title = comp.meta.title || '';
				taal = comp.meta.taal || 'Teentaal';
				tempo = comp.meta.tempo || 60;
				description = comp.meta.description || '';
				author = comp.meta.author || '';
				tagsInput = comp.meta.tags?.join(', ') || '';
				bolInput = rowsToText(comp.rows);
				editId = id;
			} else {
				errorMessage = 'Composition not found';
			}
		} catch (e) {
			console.error('Failed to load composition:', e);
			errorMessage = 'Failed to load composition';
		} finally {
			isLoading = false;
		}
	}

	// Check for edit param on mount
	onMount(() => {
		const id = $page.url.searchParams.get('edit');
		if (id) {
			loadComposition(id);
		}
	});

	// Validation
	function validate(): string | null {
		if (!title.trim()) return 'Title is required';
		if (title.trim().length < 3) return 'Title must be at least 3 characters';
		if (!bolInput.trim()) return 'Composition bols are required';
		if (rows.length === 0) return 'Could not parse any valid bols';
		if (tempo < 20 || tempo > 300) return 'Tempo must be between 20 and 300 BPM';
		return null;
	}

	async function handleSubmit() {
		errorMessage = '';
		successMessage = '';

		const validationError = validate();
		if (validationError) {
			errorMessage = validationError;
			return;
		}

		isSubmitting = true;

		try {
			// Parse tags from comma-separated input
			const tags = tagsInput
				.split(',')
				.map((t) => t.trim().toLowerCase())
				.filter((t) => t.length > 0);

			const compositionData = {
				meta: {
					title: title.trim(),
					taal,
					tempo,
					description: description.trim() || undefined,
					author: author.trim() || undefined,
					tags: tags.length > 0 ? tags : undefined
				},
				rows
			};

			if (isEditMode && editId) {
				await updateComposition(editId, compositionData);
				successMessage = 'Composition updated successfully!';
			} else {
				await createComposition(compositionData);
				successMessage = 'Composition uploaded successfully!';

				// Reset form only for new compositions
				title = '';
				bolInput = '';
				description = '';
				author = '';
				tagsInput = '';
				tempo = 60;
				taal = 'Teentaal';
			}

			// Redirect to browse page after short delay
			setTimeout(() => {
				goto('/browse');
			}, 1500);
		} catch (e) {
			console.error('Save failed:', e);
			errorMessage = 'Failed to save. Please check your connection and try again.';
		} finally {
			isSubmitting = false;
		}
	}
</script>

<svelte:head>
	<title>{isEditMode ? 'Edit' : 'Upload'} Composition - Tabla</title>
</svelte:head>

<main class="min-h-screen bg-gradient-to-b from-amber-50 to-orange-100 font-sans">
	<div class="container mx-auto px-4 py-8 max-w-2xl">
		<nav class="mb-8">
			<a href="/browse" class="text-amber-600 hover:text-amber-800">&larr; Back to Browse</a>
		</nav>

		<h1 class="text-4xl font-bold text-amber-900 mb-8">
			{isEditMode ? 'Edit Composition' : 'Upload Composition'}
		</h1>

		{#if isLoading}
			<div class="bg-white rounded-2xl shadow-lg p-8 border-2 border-amber-200 text-center">
				<p class="text-amber-700">Loading composition...</p>
			</div>
		{:else}
			<form onsubmit={(e) => { e.preventDefault(); handleSubmit(); }} class="space-y-6">
				<!-- Title (required) -->
				<div class="bg-white rounded-2xl shadow-lg p-6 border-2 border-amber-200">
					<label for="title" class="block text-lg font-semibold text-amber-900 mb-2">
						Title <span class="text-red-500">*</span>
					</label>
					<input
						type="text"
						id="title"
						bind:value={title}
						placeholder="e.g., Teentaal Theka, Kayda 1"
						class="w-full p-3 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none"
						required
					/>
				</div>

				<!-- Taal and Tempo -->
				<div class="bg-white rounded-2xl shadow-lg p-6 border-2 border-amber-200">
					<div class="grid sm:grid-cols-2 gap-4">
						<div>
							<label for="taal" class="block text-lg font-semibold text-amber-900 mb-2">
								Taal <span class="text-red-500">*</span>
							</label>
							<TaalSelector bind:value={taal} class="w-full" />
						</div>
						<div>
							<label for="tempo" class="block text-lg font-semibold text-amber-900 mb-2">
								Tempo (BPM) <span class="text-red-500">*</span>
							</label>
							<input
								type="number"
								id="tempo"
								bind:value={tempo}
								min="20"
								max="300"
								class="w-full p-2 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none"
							/>
						</div>
					</div>
				</div>

				<!-- Composition Bols (required) -->
				<div class="bg-white rounded-2xl shadow-lg p-6 border-2 border-amber-200">
					<label for="bols" class="block text-lg font-semibold text-amber-900 mb-2">
						Composition <span class="text-red-500">*</span>
					</label>
					<textarea
						id="bols"
						bind:value={bolInput}
						rows="6"
						placeholder="Enter bols separated by spaces. Use | for visual grouping. New line for new row.&#10;&#10;Example:&#10;Dha Dhin Dhin Dha | Dha Dhin Dhin Dha&#10;Dha Tin Tin Ta | Ta Dhin Dhin Dha"
						class="w-full p-3 border-2 border-amber-200 rounded-lg font-mono text-amber-900 focus:border-amber-400 focus:outline-none resize-none"
						required
					></textarea>
					<p class="mt-2 text-sm text-amber-600">
						Supported: Dha, Dhin, Ta, Tin, Na, Tun, Ge, Ke, Ti, Te, Ra, Ka, Tete, Gadi, Trkt, - (rest)
					</p>
					{#if parseError}
						<p class="mt-2 text-sm text-red-600">{parseError}</p>
					{/if}
				</div>

				<!-- Preview -->
				{#if rows.length > 0}
					<div class="bg-white rounded-2xl shadow-lg p-6 border-2 border-amber-200">
						<h2 class="text-lg font-semibold text-amber-900 mb-4">Preview</h2>
						<BolGrid {rows} currentRow={-1} currentBeat={-1} beatsPerRow={4} />
					</div>
				{/if}

				<!-- Author (optional) -->
				<div class="bg-white rounded-2xl shadow-lg p-6 border-2 border-amber-200">
					<label for="author" class="block text-lg font-semibold text-amber-900 mb-2">
						Author / Attribution
					</label>
					<input
						type="text"
						id="author"
						bind:value={author}
						placeholder="Your name or source"
						class="w-full p-3 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none"
					/>
				</div>

				<!-- Description (optional) -->
				<div class="bg-white rounded-2xl shadow-lg p-6 border-2 border-amber-200">
					<label for="description" class="block text-lg font-semibold text-amber-900 mb-2">
						Description
					</label>
					<textarea
						id="description"
						bind:value={description}
						rows="3"
						placeholder="Notes about this composition, how to practice it, etc."
						class="w-full p-3 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none resize-none"
					></textarea>
				</div>

				<!-- Tags (optional) -->
				<div class="bg-white rounded-2xl shadow-lg p-6 border-2 border-amber-200">
					<label for="tags" class="block text-lg font-semibold text-amber-900 mb-2">
						Tags
					</label>
					<input
						type="text"
						id="tags"
						bind:value={tagsInput}
						placeholder="kayda, beginner, fast (comma-separated)"
						class="w-full p-3 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none"
					/>
					<p class="mt-2 text-sm text-amber-600">
						Separate tags with commas. Helps others find your composition.
					</p>
				</div>

				<!-- Error/Success Messages -->
				{#if errorMessage}
					<div class="p-4 bg-red-100 border-2 border-red-300 rounded-xl text-red-800">
						{errorMessage}
					</div>
				{/if}
				{#if successMessage}
					<div class="p-4 bg-green-100 border-2 border-green-300 rounded-xl text-green-800">
						{successMessage}
					</div>
				{/if}

				<!-- Submit Button -->
				<button
					type="submit"
					disabled={isSubmitting}
					class="w-full p-4 bg-amber-500 hover:bg-amber-600 disabled:bg-gray-300 text-white rounded-xl font-semibold text-lg transition-colors"
				>
					{#if isSubmitting}
						{isEditMode ? 'Saving...' : 'Uploading...'}
					{:else}
						{isEditMode ? 'Save Changes' : 'Upload Composition'}
					{/if}
				</button>
			</form>
		{/if}
	</div>
</main>
