// src/routes/browse/+page.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { goto } from '$app/navigation';
	import { getCompositions, deleteComposition } from '$lib/firebase/db';
	import { getTablaPlayer, unlockAudio } from '$lib/audio';
	import { playback } from '$lib/stores/playback';
	import TaalSelector from '$lib/components/TaalSelector.svelte';
	import { TAALS } from '$lib/data/taals';
	import BolGrid from '$lib/components/BolGrid.svelte';
	import PlaybackControls from '$lib/components/PlaybackControls.svelte';
	import type { Composition, Row } from '$lib/types';
	import * as Tone from 'tone';

	// Data state
	let compositions = $state<Composition[]>([]);
	let filteredCompositions = $state<Composition[]>([]);
	let isLoading = $state(true);
	let error = $state('');

	// Filter state
	let searchQuery = $state('');
	let taalFilter = $state('All');
	let sortBy = $state<'newest' | 'oldest' | 'title'>('newest');

	// Playback state
	let audioReady = $state(false);
	let activeComposition = $state<Composition | null>(null);
	let isPlaying = $state(false);
	let currentBeat = $state(0);
	let currentRow = $state(0);
	let tempo = $state(60);

	// Subscribe to playback store
	const unsubscribe = playback.subscribe((state) => {
		isPlaying = state.isPlaying;
		currentBeat = state.currentBeat;
		currentRow = state.currentRow;
		tempo = state.tempo;
	});

	// Scheduler
	let schedulerInterval: ReturnType<typeof setInterval> | null = null;
	let nextNoteTime = 0;
	const scheduleAheadTime = 0.1;
	const lookahead = 25;

	// Filter and sort compositions
	$effect(() => {
		let result = [...compositions];

		// Filter by taal
		if (taalFilter !== 'All') {
			result = result.filter((c) => c.meta.taal === taalFilter);
		}

		// Filter by search query
		if (searchQuery.trim()) {
			const query = searchQuery.toLowerCase();
			result = result.filter(
				(c) =>
					c.meta.title?.toLowerCase().includes(query) ||
					c.meta.author?.toLowerCase().includes(query) ||
					c.meta.description?.toLowerCase().includes(query) ||
					c.meta.tags?.some((tag) => tag.toLowerCase().includes(query))
			);
		}

		// Sort
		switch (sortBy) {
			case 'newest':
				result.sort((a, b) => (b.createdAt || '').localeCompare(a.createdAt || ''));
				break;
			case 'oldest':
				result.sort((a, b) => (a.createdAt || '').localeCompare(b.createdAt || ''));
				break;
			case 'title':
				result.sort((a, b) => (a.meta.title || '').localeCompare(b.meta.title || ''));
				break;
		}

		filteredCompositions = result;
	});

	async function loadCompositions() {
		isLoading = true;
		error = '';
		try {
			compositions = await getCompositions();
		} catch (e) {
			console.error('Failed to load compositions:', e);
			error = 'Failed to load compositions. Please try again.';
		} finally {
			isLoading = false;
		}
	}

	async function initAudio() {
		await unlockAudio();
		const tabla = getTablaPlayer();
		await tabla.init();
		audioReady = true;
	}

	function scheduler() {
		if (!activeComposition) return;
		const tabla = getTablaPlayer();
		if (!tabla.ready) return;

		const rows = activeComposition.rows;

		while (nextNoteTime < Tone.now() + scheduleAheadTime) {
			const row = rows[currentRow];
			if (row && row.beats[currentBeat]) {
				const beat = row.beats[currentBeat];
				beat.bols.forEach((bol) => {
					if (bol !== '-') {
						tabla.playBol(bol, nextNoteTime);
					}
				});
			}

			const totalBeats = rows[currentRow]?.beats.length || 1;
			playback.advance(totalBeats, rows.length);
			nextNoteTime += 60 / tempo;
		}
	}

	async function playComposition(comp: Composition) {
		if (!audioReady) await initAudio();

		// Stop current playback
		stopPlayback();

		// Set up new composition
		activeComposition = comp;
		playback.setTempo(comp.meta.tempo);
		nextNoteTime = Tone.now() + 0.05;
		playback.play();
		schedulerInterval = setInterval(scheduler, lookahead);
	}

	function pausePlayback() {
		playback.pause();
		if (schedulerInterval) {
			clearInterval(schedulerInterval);
			schedulerInterval = null;
		}
	}

	function stopPlayback() {
		pausePlayback();
		playback.stop();
		activeComposition = null;
	}

	function resumePlayback() {
		if (!activeComposition) return;
		nextNoteTime = Tone.now() + 0.05;
		playback.play();
		schedulerInterval = setInterval(scheduler, lookahead);
	}

	function openInPlayer(comp: Composition) {
		// Store composition ID in URL
		goto(`/player?load=${comp.id}`);
	}

	onMount(() => {
		loadCompositions();
	});

	onDestroy(() => {
		unsubscribe();
		stopPlayback();
	});
</script>

<svelte:head>
	<title>Browse Compositions - Tabla Library</title>
</svelte:head>

<main class="min-h-screen bg-gradient-to-b from-amber-50 to-orange-100 font-sans">
	<div class="container mx-auto px-4 py-8 max-w-4xl">
		<nav class="mb-8 flex justify-between items-center">
			<a href="/" class="text-amber-600 hover:text-amber-800">&larr; Back to Home</a>
			<a
				href="/upload"
				class="px-4 py-2 bg-amber-500 hover:bg-amber-600 text-white rounded-lg font-semibold transition-colors"
			>
				+ Upload
			</a>
		</nav>

		<h1 class="text-4xl font-bold text-amber-900 mb-8">Browse Compositions</h1>

		<!-- Audio unlock -->
		{#if !audioReady}
			<button
				onclick={initAudio}
				class="w-full mb-6 p-4 bg-amber-100 border-2 border-amber-300 rounded-xl text-amber-800 hover:bg-amber-200 transition-colors"
			>
				Tap to Enable Audio
			</button>
		{/if}

		<!-- Filters -->
		<div class="bg-white rounded-2xl shadow-lg p-4 border-2 border-amber-200 mb-6">
			<div class="grid sm:grid-cols-3 gap-4">
				<!-- Search -->
				<div>
					<label for="search" class="block text-sm font-medium text-amber-700 mb-1">Search</label>
					<input
						type="text"
						id="search"
						bind:value={searchQuery}
						placeholder="Title, author, tags..."
						class="w-full p-2 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none"
					/>
				</div>

				<!-- Taal filter -->
				<div>
					<label for="taal" class="block text-sm font-medium text-amber-700 mb-1">Taal</label>
					<select
						id="taal"
						bind:value={taalFilter}
						class="w-full p-2 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none bg-white"
					>
						<option value="All">All Taals</option>
						{#each Object.keys(TAALS) as taal}
							<option value={taal}>{taal}</option>
						{/each}
					</select>
				</div>

				<!-- Sort -->
				<div>
					<label for="sort" class="block text-sm font-medium text-amber-700 mb-1">Sort by</label>
					<select
						id="sort"
						bind:value={sortBy}
						class="w-full p-2 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none bg-white"
					>
						<option value="newest">Newest first</option>
						<option value="oldest">Oldest first</option>
						<option value="title">Title A-Z</option>
					</select>
				</div>
			</div>
		</div>

		<!-- Results count -->
		<p class="text-amber-700 mb-4">
			{#if isLoading}
				Loading...
			{:else if error}
				<span class="text-red-600">{error}</span>
			{:else}
				Showing {filteredCompositions.length} of {compositions.length} compositions
			{/if}
		</p>

		<!-- Composition list -->
		{#if !isLoading && !error}
			<div class="space-y-4">
				{#each filteredCompositions as comp (comp.id)}
					<div class="bg-white rounded-2xl shadow-lg border-2 border-amber-200 overflow-hidden">
						<!-- Header -->
						<div class="p-4 border-b border-amber-100">
							<div class="flex justify-between items-start">
								<div>
									<h2 class="text-xl font-semibold text-amber-900">
										{comp.meta.title || 'Untitled'}
									</h2>
									<div class="flex flex-wrap gap-2 mt-1 text-sm text-amber-600">
										<span class="bg-amber-100 px-2 py-0.5 rounded">{comp.meta.taal}</span>
										<span>{comp.meta.tempo} BPM</span>
										{#if comp.meta.author}
											<span>by {comp.meta.author}</span>
										{/if}
									</div>
								</div>
								<div class="flex gap-2">
									{#if activeComposition?.id === comp.id && isPlaying}
										<button
											onclick={pausePlayback}
											class="p-2 bg-amber-500 hover:bg-amber-600 text-white rounded-lg transition-colors"
											title="Pause"
										>
											<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
												<path
													fill-rule="evenodd"
													d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zM7 8a1 1 0 012 0v4a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v4a1 1 0 102 0V8a1 1 0 00-1-1z"
													clip-rule="evenodd"
												/>
											</svg>
										</button>
									{:else if activeComposition?.id === comp.id}
										<button
											onclick={resumePlayback}
											class="p-2 bg-amber-500 hover:bg-amber-600 text-white rounded-lg transition-colors"
											title="Resume"
										>
											<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
												<path
													fill-rule="evenodd"
													d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z"
													clip-rule="evenodd"
												/>
											</svg>
										</button>
									{:else}
										<button
											onclick={() => playComposition(comp)}
											class="p-2 bg-amber-500 hover:bg-amber-600 text-white rounded-lg transition-colors"
											title="Play"
										>
											<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
												<path
													fill-rule="evenodd"
													d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z"
													clip-rule="evenodd"
												/>
											</svg>
										</button>
									{/if}
									<button
										onclick={() => openInPlayer(comp)}
										class="p-2 bg-amber-100 hover:bg-amber-200 text-amber-800 rounded-lg transition-colors"
										title="Open in Player"
									>
										<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
											/>
										</svg>
									</button>
								</div>
							</div>

							{#if comp.meta.description}
								<p class="mt-2 text-amber-700 text-sm">{comp.meta.description}</p>
							{/if}

							{#if comp.meta.tags && comp.meta.tags.length > 0}
								<div class="flex flex-wrap gap-1 mt-2">
									{#each comp.meta.tags as tag}
										<span class="text-xs bg-amber-50 text-amber-600 px-2 py-0.5 rounded-full border border-amber-200">
											{tag}
										</span>
									{/each}
								</div>
							{/if}
						</div>

						<!-- Bol Grid Preview (collapsed) -->
						<div class="p-4 bg-amber-50">
							<BolGrid
								rows={comp.rows}
								currentRow={activeComposition?.id === comp.id ? currentRow : -1}
								currentBeat={activeComposition?.id === comp.id ? currentBeat : -1}
								beatsPerRow={4}
							/>
						</div>
					</div>
				{:else}
					<div class="bg-white rounded-2xl shadow-lg p-8 border-2 border-amber-200 text-center">
						<p class="text-amber-700">No compositions found matching your filters.</p>
						<a href="/upload" class="inline-block mt-4 text-amber-600 hover:text-amber-800 underline">
							Be the first to upload one!
						</a>
					</div>
				{/each}
			</div>
		{/if}
	</div>
</main>

// src/app/browse/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { getCompositions } from '@/lib/firebase/db';
import { TAALS } from '@/lib/types';
import BolGrid from '@/components/BolGrid';
import type { Composition } from '@/lib/types';

export default function BrowsePage() {
  const [compositions, setCompositions] = useState<Composition[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [taalFilter, setTaalFilter] = useState('');
  const [sortBy, setSortBy] = useState<'newest' | 'oldest' | 'title'>('newest');
  const [expandedId, setExpandedId] = useState<string | null>(null);

  useEffect(() => {
    getCompositions()
      .then(setCompositions)
      .finally(() => setLoading(false));
  }, []);

  // Filter and sort
  const filtered = compositions
    .filter((comp) => {
      const matchesSearch =
        !search ||
        comp.meta.title?.toLowerCase().includes(search.toLowerCase()) ||
        comp.meta.author?.toLowerCase().includes(search.toLowerCase()) ||
        comp.meta.description?.toLowerCase().includes(search.toLowerCase()) ||
        comp.meta.tags?.some((tag) =>
          tag.toLowerCase().includes(search.toLowerCase())
        );
      const matchesTaal = !taalFilter || comp.meta.taal === taalFilter;
      return matchesSearch && matchesTaal;
    })
    .sort((a, b) => {
      if (sortBy === 'title') {
        return (a.meta.title || '').localeCompare(b.meta.title || '');
      }
      const dateA = new Date(a.createdAt || 0).getTime();
      const dateB = new Date(b.createdAt || 0).getTime();
      return sortBy === 'newest' ? dateB - dateA : dateA - dateB;
    });

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  return (
    <main className="min-h-screen p-4 sm:p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <header className="flex items-center justify-between mb-6">
          <Link
            href="/"
            className="text-amber-600 hover:text-amber-800 font-medium"
          >
            ← Home
          </Link>
          <h1 className="text-2xl font-bold text-amber-900">Browse</h1>
          <Link
            href="/upload"
            className="bg-amber-500 text-white px-4 py-2 rounded-xl font-medium hover:bg-amber-600 active:scale-95 transition-all"
          >
            + New
          </Link>
        </header>

        {/* Filters */}
        <div className="bg-white rounded-2xl shadow-lg border-2 border-amber-200 p-4 mb-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {/* Search */}
            <input
              type="text"
              placeholder="Search..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="p-3 bg-amber-50 border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none"
            />

            {/* Taal Filter */}
            <select
              value={taalFilter}
              onChange={(e) => setTaalFilter(e.target.value)}
              className="p-3 bg-amber-50 border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none"
            >
              <option value="">All Taals</option>
              {Object.keys(TAALS).map((taal) => (
                <option key={taal} value={taal}>
                  {taal}
                </option>
              ))}
            </select>

            {/* Sort */}
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as typeof sortBy)}
              className="p-3 bg-amber-50 border-2 border-amber-200 rounded-xl text-amber-900 focus:border-amber-400 focus:outline-none"
            >
              <option value="newest">Newest First</option>
              <option value="oldest">Oldest First</option>
              <option value="title">By Title</option>
            </select>
          </div>
        </div>

        {/* Results */}
        {loading ? (
          <div className="text-center text-amber-600 py-12">Loading...</div>
        ) : filtered.length === 0 ? (
          <div className="text-center text-amber-600 py-12">
            No compositions found
          </div>
        ) : (
          <div className="space-y-4">
            {filtered.map((comp) => {
              const isExpanded = expandedId === comp.id;

              return (
                <div
                  key={comp.id}
                  className="bg-white rounded-2xl shadow-lg border-2 border-amber-200 overflow-hidden"
                >
                  {/* Header - always visible */}
                  <div
                    className="p-4 sm:p-6 cursor-pointer hover:bg-amber-50 transition-colors"
                    onClick={() => toggleExpand(comp.id)}
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="text-amber-400 text-lg">
                            {isExpanded ? '▼' : '▶'}
                          </span>
                          <h2 className="text-lg font-semibold text-amber-900 truncate">
                            {comp.meta.title || 'Untitled'}
                          </h2>
                        </div>
                        <div className="flex flex-wrap gap-2 mt-2 ml-6">
                          <span className="px-2 py-1 bg-amber-100 text-amber-700 rounded text-sm">
                            {comp.meta.taal}
                          </span>
                          <span className="px-2 py-1 bg-amber-100 text-amber-700 rounded text-sm">
                            {comp.meta.tempo} BPM
                          </span>
                          {comp.meta.author && (
                            <span className="text-amber-500 text-sm">
                              by {comp.meta.author}
                            </span>
                          )}
                        </div>
                      </div>
                      <div className="flex gap-2" onClick={(e) => e.stopPropagation()}>
                        <Link
                          href={`/player?load=${comp.id}`}
                          className="px-4 py-2 bg-amber-500 text-white rounded-xl font-medium hover:bg-amber-600 active:scale-95 transition-all"
                        >
                          Play
                        </Link>
                        <Link
                          href={`/upload?edit=${comp.id}`}
                          className="px-4 py-2 bg-white border-2 border-amber-200 text-amber-700 rounded-xl font-medium hover:border-amber-400 active:scale-95 transition-all"
                        >
                          Edit
                        </Link>
                      </div>
                    </div>
                  </div>

                  {/* Expanded content */}
                  {isExpanded && (
                    <div className="border-t-2 border-amber-100 p-4 sm:p-6 bg-amber-50/50">
                      {/* Description */}
                      {comp.meta.description && (
                        <p className="text-amber-700 mb-4">
                          {comp.meta.description}
                        </p>
                      )}

                      {/* Tags */}
                      {comp.meta.tags && comp.meta.tags.length > 0 && (
                        <div className="flex flex-wrap gap-1 mb-4">
                          {comp.meta.tags.map((tag) => (
                            <span
                              key={tag}
                              className="px-2 py-0.5 bg-amber-100 text-amber-600 rounded text-xs"
                            >
                              #{tag}
                            </span>
                          ))}
                        </div>
                      )}

                      {/* Full composition grid */}
                      <div className="bg-white rounded-xl p-4 border border-amber-200">
                        <BolGrid rows={comp.rows} />
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </main>
  );
}
