// src/components/BolGrid.tsx
'use client';

import type { Row } from '@/lib/types';

interface BolGridProps {
  rows: Row[];
  currentBeat?: number;
  currentRow?: number;
  beatsPerRow?: number;
}

export default function BolGrid({
  rows,
  currentBeat = -1,
  currentRow = -1,
  beatsPerRow = 4,
}: BolGridProps) {
  let globalBeatIndex = 0;

  return (
    <div className="space-y-2">
      {rows.map((row, rowIndex) => (
        <div
          key={rowIndex}
          className="flex flex-wrap gap-1 sm:gap-2"
        >
          {row.beats.map((beat, beatIndex) => {
            const isCurrentBeat =
              rowIndex === currentRow && beatIndex === currentBeat;
            const beatGlobalIndex = globalBeatIndex++;
            const isFirstBeatOfGroup = beatGlobalIndex % beatsPerRow === 0;

            return (
              <div
                key={beatIndex}
                className={`
                  flex-1 min-w-[3rem] sm:min-w-[4rem] p-2 sm:p-3
                  rounded-lg text-center font-semibold
                  transition-all duration-100
                  ${isCurrentBeat
                    ? 'bg-amber-500 text-white scale-105 shadow-lg'
                    : 'bg-white border-2 border-amber-200 text-amber-900'
                  }
                  ${isFirstBeatOfGroup && beatIndex > 0 ? 'ml-2 sm:ml-4' : ''}
                `}
              >
                {beat.bols.map((bol, bolIndex) => (
                  <span
                    key={bolIndex}
                    className={`${beat.bols.length > 1 ? 'text-xs sm:text-sm' : 'text-sm sm:text-base'}`}
                  >
                    {bol}
                    {bolIndex < beat.bols.length - 1 && (
                      <span className="text-amber-400 mx-0.5">·</span>
                    )}
                  </span>
                ))}
              </div>
            );
          })}
        </div>
      ))}
    </div>
  );
}

// src/lib/components/BolGrid.svelte
<script lang="ts">
	import type { Row } from '$lib/types';

	interface Props {
		rows: Row[];
		currentRow?: number;
		currentBeat?: number;
		beatsPerRow?: number;
	}

	let { rows, currentRow = -1, currentBeat = -1, beatsPerRow = 4 }: Props = $props();

	// Group beats into vibhags (visual groupings)
	function groupBeats(beats: { bols: string[] }[], groupSize: number) {
		const groups: { bols: string[] }[][] = [];
		for (let i = 0; i < beats.length; i += groupSize) {
			groups.push(beats.slice(i, i + groupSize));
		}
		return groups;
	}
</script>

<div class="bol-grid space-y-1">
	{#each rows as row, rowIdx}
		<div
			class="row flex flex-wrap gap-1 p-2 rounded-lg transition-colors duration-150"
			class:bg-amber-100={currentRow === rowIdx}
			class:bg-white={currentRow !== rowIdx}
		>
			{#each groupBeats(row.beats, beatsPerRow) as group, groupIdx}
				<div class="vibhag flex gap-0.5 px-1.5 py-0.5 border-l-2 border-amber-300 first:border-l-0">
					{#each group as beat, beatIdx}
						{@const globalBeatIdx = groupIdx * beatsPerRow + beatIdx}
						<div
							class="beat flex items-center justify-center min-w-[2rem] px-1 py-1 rounded font-mono text-sm transition-all duration-100"
							class:bg-amber-500={currentRow === rowIdx && currentBeat === globalBeatIdx}
							class:text-white={currentRow === rowIdx && currentBeat === globalBeatIdx}
							class:scale-105={currentRow === rowIdx && currentBeat === globalBeatIdx}
							class:bg-amber-50={!(currentRow === rowIdx && currentBeat === globalBeatIdx)}
							class:text-amber-900={!(currentRow === rowIdx && currentBeat === globalBeatIdx)}
						>
							{#each beat.bols as bol, bolIdx}
								<span class:ml-0.5={bolIdx > 0}>{bol}</span>
							{/each}
						</div>
					{/each}
				</div>
			{/each}
		</div>
	{/each}
</div>

{#if rows.length === 0}
	<div class="text-center text-amber-600 py-8">
		No composition loaded. Enter bols above or load a saved composition.
	</div>
{/if}
