// src/components/TaalSelector.tsx
'use client';

import { TAALS } from '@/lib/types';

interface TaalSelectorProps {
  value: string;
  onChange: (taal: string) => void;
  disabled?: boolean;
}

export default function TaalSelector({
  value,
  onChange,
  disabled = false,
}: TaalSelectorProps) {
  const taalNames = Object.keys(TAALS);

  return (
    <div className="w-full">
      <label className="block text-amber-700 font-medium mb-2">Taal</label>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        className="w-full p-3 bg-white border-2 border-amber-200 rounded-xl text-amber-900 font-medium focus:border-amber-400 focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {taalNames.map((taal) => (
          <option key={taal} value={taal}>
            {taal} ({TAALS[taal].beats} beats)
          </option>
        ))}
      </select>
    </div>
  );
}

// src/lib/components/TaalSelector.svelte
<script lang="ts">
	import { TAALS } from '$lib/data/taals';

	interface Props {
		value: string;
		onchange?: (taal: string) => void;
		showBeats?: boolean;
		class?: string;
	}

	let { value = $bindable(), onchange, showBeats = true, class: className = '' }: Props = $props();

	function handleChange(e: Event) {
		const target = e.target as HTMLSelectElement;
		value = target.value;
		onchange?.(target.value);
	}
</script>

<select
	{value}
	onchange={handleChange}
	class="p-2 border-2 border-amber-200 rounded-lg focus:border-amber-400 focus:outline-none bg-white {className}"
>
	{#each Object.entries(TAALS) as [key, taal]}
		<option value={key}>
			{taal.name}{showBeats ? ` (${taal.beats})` : ''}
		</option>
	{/each}
</select>
